# manifest.toml — cosmic-comp

[package]
name             = "cosmic-comp"
version          = "1.7.0"
description      = "COSMIC Wayland compositor, systemd-free (login1 via quantra-logind + oxibus)"
license          = "GPL-3.0-only"
maintainer       = "Ali Zain <alizain@zainiumdynamics.tech>"
homepage         = "https://github.com/pop-os/cosmic-comp"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

depends          = ["libseat", "libinput", "wayland", "mesa", "quantra-logind"]
provides         = ["cosmic-comp"]
tags             = ["desktop", "cosmic", "compositor"]

[install]
bin     = "/overlayer/syshub/bin"
share   = "/overlayer/syshub/share"
_syshub = true

[remove]
files    = []
dirs     = []
symlinks = []

[hooks]
