# manifest.toml — cosmic-randr (userland tier)

[package]
name             = "cosmic-randr"
version          = "1.7.0"
description      = "Display configuration library for the COSMIC Desktop Environment"
license          = "MPL-2.0"
maintainer       = "Ali Zain <alizain@zainiumdynamics.tech>"
homepage         = "https://github.com/pop-os/cosmic-randr"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

depends          = ["wayland"]
provides         = ["cosmic-randr"]
tags             = ["desktop", "cosmic"]

[install]
bin     = "/overlayer/syshub/bin"
_syshub = true

[remove]
files    = []
dirs     = []
symlinks = []

[hooks]
