# manifest.toml — plymouth

[package]
name             = "plymouth"
version          = "26.134.222"
description      = "Boot splash"
license          = "GPL-2.0-or-later"
maintainer       = "Ali Zain <alizain@zainiumdynamics.tech>"
homepage         = "https://www.freedesktop.org/wiki/Software/Plymouth/"
build_type       = "dynamic"
libc_target      = "musl"

blake3           = ""
ed25519_sig      = ""
ed25519_pubkey   = ""

depends          = ["systemd"]
provides         = ["plymouth"]
tags             = ["boot", "base"]

[install]
bin     = "/overlayer/syshub/bin"
lib     = "/overlayer/syshub/lib"
share   = "/overlayer/syshub/share"
etc     = "/overlayer/syshub/etc"
_syshub = true

[remove]
files    = []
dirs     = []
symlinks = []

[hooks]
